### ISSUE TITLE
How to run list of commands?

### ISSUE THREAD

**Issue by yabitbul** [StackStorm-Exchange/stackstorm-exos#7]
when I add more then one command, it returns an error in output, but status of the action is Succeed

**Comment by LindsayHill** [comment]
What was the complete st2 command you used? It looks like this action should take a list of commands.

**Comment by yabitbul** [comment]
I'm trying to run it via GUI
![image](https://user-images.githubusercontent.com/39561006/41052435-bfff6eac-6986-11e8-96b0-8e4cac9e0390.png)

**Comment by LindsayHill** [comment]
It's a bit hard to tell what's happening from that screenshot, because it's only showing part of what's happening.

Go to the CLI on your ST2 system, and run `st2 execution list`. Identify the execution ID for when you ran that EXOS command, and then run `st2 execution get <ID>`. Paste that output here.

**Comment by yabitbul** [comment]
```shell
ubuntu@bwc:~$ st2 execution get 5b183d2f7c1d96161d5c66be
id: 5b183d2f7c1d96161d5c66be
action.ref: default.Yulia_test
parameters:
  cmd: 'show vlan
    show switch
    show licenses'
  mgmt_ip: 10.67.72.94
  password: yulia
  username: yulia
status: succeeded (21s elapsed)
result_task: run_exos_cmd
result:
  exit_code: 0
  result:
    error: error processing command show vlan
show switch
show licenses
  stderr: 'st2.actions.python.ExosCmd: DEBUG    Creating new Client object.
No handlers could be found for logger "st2.st2common.util.api"
st2.actions.python.ExosCmd: DEBUG    Retrieving value from the datastore (name=exos.ExosCmd:cookie)
st2.actions.python.ExosCmd: DEBUG    Setting value in the datastore (name=exos.ExosCmd:cookie)
'
  stdout: ''
start_timestamp: Wed, 06 Jun 2018 19:59:43 UTC
end_timestamp: Wed, 06 Jun 2018 20:00:04 UTC
+--------------------------+-------------------------+--------------------------+--------------------------+--------------------------+
| id                       | status                  | task                     | action                   | start_timestamp          |
+--------------------------+-------------------------+--------------------------+--------------------------+--------------------------+
| 5b183d2f7c1d96161d5c66c1 | succeeded (16s elapsed) | register_device_credenti | network_essentials.regis | Wed, 06 Jun 2018         |
|                          |                         | als                      | ter_device_credentials   | 19:59:43 UTC             |
| 5b183d3f7c1d96161d5c66c4 | succeeded (1s elapsed)  | run_exos_cmd             | exos.cmd                 | Wed, 06 Jun 2018         |
|                          |                         |                          |                          | 19:59:59 UTC             |
+--------------------------+-------------------------+--------------------------+--------------------------+--------------------------+
```

**Comment by yabitbul** [comment]
![image](https://user-images.githubusercontent.com/39561006/41062350-92b194d0-69a3-11e8-9b4f-5ebd072c5143.png)

**Comment by yabitbul** [comment]
I changed a little cmd.py, It takes list of commands 

class ExosCmd(Action):

    def run(self, ipaddress='10.68.65.81', cmd=''):
        """
        Run an EXOS command on the remote switch
        Args:
            - ip_address: The IP address of the switch
            - username: login user name
            - password: login password
            - cmd: either a single EXOS command or list of EXOS commands
        Raises:
            - ValueError: On switch reponse being invalid
            - RuntimeError: if switch cannot process the command
        Returns:
            dict: with EXOS CLI results
        """
        cmd_list = cmd.split(",")
        jsonrpc = JsonRPC(ipaddress, self.config['username'], self.config['password'])
        jsonrpc.cookie = self.action_service.get_value('cookie')

        try:
            result = ''
            for command in cmd_list:
                command = command.strip()
                response = jsonrpc.send(command)
                self.action_service.set_value(name='cookie', value=jsonrpc.cookie)
                result += str(response)
            return result
        except Exception:
                sys.exit(1)

**Comment by LindsayHill** [comment]
I think that a better approach here might be to change the action [metadata](https://github.com/StackStorm-Exchange/stackstorm-exos/blob/master/actions/cmd.yaml#L14) to have `type: array`, rather than `type: string`. 

This is a little better than splitting on `,` inside the code, as ST2 can handle a variety of ways of providing an array.
